parameters:
    parsley_server_form.class: Parsley\ServerBundle\Form\FormType
    parsley_server_form_generator.class: Parsley\ServerBundle\Form\Generator

services:
    form.type.form:
        class: %parsley_server_form.class%
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: form}
    parsley_server_form_generator:
        class: %parsley_server_form_generator.class%
        arguments: [@service_container]
